# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 15:36
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('subintro_title', models.CharField(blank=True, max_length=256, verbose_name='\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0432 subintro')),
                ('subintro_text', models.CharField(blank=True, max_length=512, verbose_name='\u0442\u0435\u043a\u0441\u0442 \u0432 subintro')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='\u043a\u043e\u043d\u0442\u0435\u043d\u0442')),
                ('slug', models.SlugField(blank=True, help_text='\u0417\u0430\u043f\u043e\u043b\u043d\u044f\u0442\u044c \u043d\u0435 \u043d\u0443\u0436\u043d\u043e', unique=True, verbose_name='\u0441\u043b\u0430\u0433')),
            ],
            options={
                'verbose_name': '\u0441\u0442\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430',
                'verbose_name_plural': '\u0441\u0442\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b',
            },
        ),
    ]
