# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 20:02
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='\u043a\u043e\u043d\u0442\u0435\u043d\u0442'),
        ),
    ]
