# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-order'], 'verbose_name': '\u0441\u0442\u0430\u0442\u044c\u044f', 'verbose_name_plural': '\u0441\u0442\u0430\u0442\u044c\u0438'},
        ),
        migrations.AddField(
            model_name='article',
            name='order',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='\u043f\u043e\u0440\u044f\u0434\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='article',
            name='show',
            field=models.BooleanField(default=False, verbose_name='\u043f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u043d\u0430 \u0441\u0430\u0439\u0442\u0435'),
        ),
    ]
