# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u0418\u043c\u044f')),
                ('email', models.EmailField(blank=True, max_length=256, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=256, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('comment', models.TextField(blank=True, verbose_name='\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0437\u0430\u043a\u0430\u0437\u0430')),
                ('brief', models.FileField(blank=True, max_length=256, null=True, upload_to=b'uploads/briefs', verbose_name='\u0411\u0440\u0438\u0444')),
            ],
            options={
                'ordering': ['-order_date'],
                'verbose_name': '\u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u044f',
            },
        ),
    ]
