# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=256, upload_to=b'uploads/items', verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('order', models.IntegerField(blank=True, default=100, null=True, verbose_name='\u043f\u043e\u0440\u044f\u0434\u043e\u043a \u0441\u043e\u0440\u0442\u0438\u0440\u043e\u0432\u043a\u0438')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': '\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('href', models.CharField(blank=True, max_length=256, verbose_name='\u0441\u0441\u044b\u043b\u043a\u0430')),
                ('desc', models.TextField(blank=True, verbose_name='\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('order', models.SmallIntegerField(blank=True, default=0, verbose_name='\u043f\u043e\u0440\u044f\u0434\u043e\u043a')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('tags', models.CharField(blank=True, max_length=256, verbose_name='\u0442\u0435\u0433\u0438')),
                ('date', models.DateField(blank=True, verbose_name='\u0434\u0430\u0442\u0430 \u0432\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u044f \u043f\u0440\u043e\u0435\u043a\u0442\u0430')),
            ],
            options={
                'ordering': ['-order'],
                'verbose_name': '\u0440\u0430\u0431\u043e\u0442\u0430',
                'verbose_name_plural': '\u0440\u0430\u0431\u043e\u0442\u044b',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='portfolio.Work', verbose_name='\u0440\u0430\u0431\u043e\u0442\u0430'),
        ),
    ]
